---
# handlers file for jenkins

- name: restart jenkins 
  service: name=jenkins state=restarted enabled=yes

- name: configure default users 
  user: name=jenkins shell=/bin/bash groups=wheel state=present generate_ssh_key=yes ssh_key_type=rsa ssh_key_file=/var/lib/jenkins/.ssh/jenkinskey
